Conditional network update
KIT-CMS/htt-ml pull request #5
Opened 2019-11-22 13:03 UTC by sijoerger

Code is tested up until production of shapes, this includes production of training datasets, training, testing and production of NN Score friend trees.

After this update is merged I will make a pull request for sm-htt-analysis where the new master of htt-ml will be head.

2019-11-22 16:49 UTC, swozniewski approved these changes
Danke! Sieht sehr gut aus. Wie besprochen noch den switch für die randomization einfügen, dann passt es von meiner Seite aus.

2019-11-22 16:51 UTC, swozniewski commented
> Danke! Sieht sehr gut aus. Wie besprochen noch den switch für die randomization einfügen, dann passt es von meiner Seite aus.

ok, da ist es ja schon...

2019-11-25 08:48 UTC, mova commented on training/keras_training.py
> -    w = np.vstack(w) * config["global_weight_scale"]  # weights
sollen wir die global_weight_scale: 1.0 dann aus den traing templates raus nehmen?

2019-11-25 09:08 UTC, sijoerger commented on training/keras_training.py
> -    w = np.vstack(w) * config["global_weight_scale"]  # weights
KÖnnen wir, ich seh keinen wirklichen Sinn dahinter, die drin zu behalten.

2019-11-25 09:08 UTC, merged

2019-11-25 09:41 UTC, mova requested changes

2019-11-25 09:41 UTC, mova commented on training/keras_training.py
> +    z = []
hier sollte man kommentieren was z sein soll.

2019-11-25 09:41 UTC, mova commented on training/keras_training.py
> -    setup_logging(logging.DEBUG,"{}/training{}.log".format(config["output_path"], args.fold))
?

2019-11-25 09:41 UTC, mova commented on training/keras_training.py
> +        eras = ['all']
all? -> any?

2019-11-25 09:41 UTC, mova commented on training/keras_training.py
> +        eraIndexDict={era: {label: np.where((z_train[:,i_era] == 1) & (y_train[:,i_class] == 1))[0] for i_class, label in enumerate(classes)} for i_era, era in enumerate(eras)}
hier fehlt ein kommentar :)

2019-11-25 09:41 UTC, mova commented on training/keras_training.py
> +            testIndexDict = {
defines the indices of the correct answers  for the each era / class combination

2019-11-25 09:41 UTC, mova commented on training/keras_training.py
> +    z = []
list of matrices that are 0/1 depening if then index for the event is in that era or not